name: Twice Daily Auto Commit

on:
  schedule:
    # Run this workflow every 12 hours
    - cron: "0 */12 * * *"
    
  schedule-dispacher:

jobs:
  daily-commit-job:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Explicit write access to repository contents

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Updated to v3

      - name: Update File with Today's Date
        run: |
          # Set timezone to Kolkata (IST)
          export TZ="Asia/Kolkata"
          echo "Auto commit on $(date +"%Y-%m-%d %I:%M:%S %p")" >> daily-log.txt

      - name: Commit Changes
        run: |
          # Set timezone to Kolkata (IST)
          export TZ="Asia/Kolkata"
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add daily-log.txt
          git commit -m "auto-commit-$(date +'%Y-%m-%d-%I-%M %p')"
          git push
